import type { NextPage } from "next";
import Head from "next/head";
import homeStyles from "../styles/Home.module.sass";
import Nav from "../components/Nav";
import NewsSection from "../components/NewsSection";
import Streams from "../components/Streams";
import Footer from "../components/Footer";
import NewsContext from "../components/NewsContext";

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/articles");
  const data = await res.json();
  return {
    props: {
      articles: data,
    }, // will be passed to the page component as props
  };
}

const Home: NextPage = ({ articles }) => {
  return (
    <div className={homeStyles.app}>
      <Head>
        <title>CS:GO News & Coverage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <NewsContext.Provider value={{ articles }}>
        <Nav />
        <NewsSection />
        <Streams />
        <Footer />
      </NewsContext.Provider>
    </div>
  );
};

export default Home;
